In [ ]:
import os
import pandas as pd
import numpy as np
from os.path import dirname, abspath

In [ ]:
directory_path = "C:\\Users\\kripa\\Documents\\Intro_to_ML_TMLC"

In [ ]:
if os.path.exists(directory_path):
    # Change the current working directory to the specified directory
    os.chdir(directory_path)
    print(f"Directory changed to: {directory_path}")
else:
    print(f"The specified directory '{directory_path}' does not exist.")

The specified directory 'C:\Users\kripa\Documents\Intro_to_ML_TMLC' does not exist.

In [ ]:
df = pd.read_csv("Train.csv")

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,5728806,Large private room in Nolita,4271676,Nat,Manhattan,Nolita,40.72217,-73.99481,Private room,120,7,3,2015-09-01,0.06,3,0
1,2243769,Super Bowl New York City Apartment,11460768,Brian,Manhattan,Upper West Side,40.80020,-73.96045,Entire home/apt,1500,1,0,NaN,NaN,1,0
2,35515415,COZY APT CLOSE TO LGA & JFK AND TRANSPORTATION,267193767,Jenny,Queens,East Elmhurst,40.75558,-73.89316,Entire home/apt,200,2,4,2019-07-05,4.00,1,365
3,36202006,Stream-Pressed Paradise (Laundry Room Setup),43392243,Rita,Staten Island,Concord,40.60110,-74.07830,Shared room,30,2,0,NaN,NaN,4,82
4,3780951,Charming Harlem apartment,16065171,Gina,Manhattan,Harlem,40.81022,-73.94266,Shared room,115,1,16,2019-05-26,0.27,1,365

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34226 entries, 0 to 34225
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              34226 non-null  int64
 1   name                            34214 non-null  object
 2   host_id                         34226 non-null  int64
 3   host_name                       34213 non-null  object
 4   neighbourhood_group             34226 non-null  object
 5   neighbourhood                   34226 non-null  object
 6   latitude                        34226 non-null  float64
 7   longitude                       34226 non-null  float64
 8   room_type                       34226 non-null  object
 9   price                           34226 non-null  int64
 10  minimum_nights                  34226 non-null  int64
 11  number_of_reviews               34226 non-null  int64
 12  last_review                     27244 non-null  object
 13  reviews_per_month               27244 non-null  float64
 14  calculated_host_listings_count  34226 non-null  int64
 15  availability_365                34226 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 4.2+ MB

In [ ]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,3.422600e+04,3.422600e+04,34226.000000,34226.000000,34226.000000,34226.000000,34226.000000,27244.000000,34226.000000,34226.000000
mean,1.898209e+07,6.733847e+07,40.729059,-73.952070,153.480979,6.953690,23.390931,1.377074,7.093905,113.301730
std,1.097597e+07,7.833091e+07,0.054604,0.046161,243.312608,20.255833,44.476822,1.688953,32.828412,131.892814
min,2.595000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.460366e+06,7.824440e+06,40.690040,-73.983150,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.965371e+07,3.065628e+07,40.722995,-73.955700,107.000000,2.000000,5.000000,0.730000,1.000000,45.000000
75%,2.908201e+07,1.074344e+08,40.763200,-73.935982,175.000000,5.000000,24.000000,2.020000,2.000000,229.000000
max,3.648724e+07,2.743115e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [ ]:
df.shape

(34226, 16)

In [ ]:
df.isnull().sum()

id                                   0
name                                12
host_id                              0
host_name                           13
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                       6982
reviews_per_month                 6982
calculated_host_listings_count       0
availability_365                     0
dtype: int64

In [ ]:
df['neighbourhood'].unique()

array(['Nolita', 'Upper West Side', 'East Elmhurst', 'Concord', 'Harlem',
       'Battery Park City', 'Rosedale', 'Fort Greene', 'Chelsea',
       'Washington Heights', 'Kensington', 'Williamsburg',
       "Hell's Kitchen", 'Sunset Park', 'Crown Heights', 'Civic Center',
       'Bushwick', 'Inwood', 'Greenpoint', 'Long Island City',
       'Carroll Gardens', 'Prospect-Lefferts Gardens', 'Astoria',
       'Bedford-Stuyvesant', 'Boerum Hill', 'Murray Hill', 'Flushing',
       'Upper East Side', 'Chinatown', 'Woodside', 'Midtown',
       'Breezy Point', 'Sheepshead Bay', 'Flatiron District',
       'East Harlem', 'Downtown Brooklyn', 'Financial District',
       'East Village', 'Sunnyside', 'Greenwich Village', 'Middle Village',
       'Roosevelt Island', 'Ditmars Steinway', 'Ridgewood',
       'Lower East Side', 'Theater District', 'Bay Ridge', 'Park Slope',
       'Prospect Heights', 'Tompkinsville', 'Morningside Heights',
       'West Village', 'Gramercy', 'Throgs Neck', 'East Flatbush',
       'Brighton Beach', 'Forest Hills', 'Tribeca', 'Jackson Heights',
       'Gowanus', 'Kips Bay', 'Flatbush', 'Port Morris', 'Ozone Park',
       'Elmhurst', 'Bensonhurst', 'Clason Point', 'SoHo', 'Clinton Hill',
       'Jamaica', 'Two Bridges', 'Little Italy', 'DUMBO', 'Bayswater',
       'Soundview', 'East New York', 'Brooklyn Heights', 'Mott Haven',
       'Kingsbridge', 'Windsor Terrace', 'Red Hook', 'Brownsville',
       'Springfield Gardens', 'Highbridge', 'Jamaica Estates',
       'Concourse Village', 'West Brighton', 'New Brighton', 'Midwood',
       'South Slope', 'Rego Park', 'Woodlawn', 'St. Albans', 'Longwood',
       'Rockaway Beach', 'Canarsie', 'Columbia St', 'Fordham',
       'Wakefield', 'Briarwood', 'Fieldston', 'Howard Beach',
       'Parkchester', 'Claremont Village', 'Grant City', 'Fort Hamilton',
       'Concourse', 'Flatlands', 'South Ozone Park', 'Queens Village',
       'Richmond Hill', 'Baychester', 'Kew Gardens Hills', 'Morrisania',
       'Hunts Point', 'Great Kills', 'Arverne', 'Schuylerville',
       'Morris Heights', 'Borough Park', 'Cobble Hill', 'Hollis',
       'Woodhaven', 'Melrose', 'Randall Manor', 'Sea Gate',
       'Stuyvesant Town', 'Maspeth', 'Port Richmond', 'Bath Beach',
       'Belmont', 'University Heights', 'Westerleigh', 'Arden Heights',
       'Coney Island', 'Fresh Meadows', 'Stapleton', 'Corona',
       'Kew Gardens', 'Eastchester', 'Cypress Hills', 'Vinegar Hill',
       'Manhattan Beach', 'Glendale', 'Bellerose', 'Clifton',
       'Williamsbridge', 'Pelham Bay', 'Arrochar', 'NoHo',
       'College Point', 'Gravesend', 'Far Rockaway', 'New Dorp Beach',
       'Emerson Hill', 'Navy Yard', 'St. George', 'Allerton', 'Unionport',
       'North Riverdale', 'Pelham Gardens', 'City Island', 'Little Neck',
       'Tottenville', 'Norwood', 'Edgemere', 'Mount Hope', 'Mount Eden',
       'Cambria Heights', 'Bayside', 'Grymes Hill', 'Laurelton',
       'Edenwald', 'Whitestone', 'Bronxdale', 'Marble Hill', 'Tremont',
       'Silver Lake', 'Bay Terrace, Staten Island', 'Morris Park',
       'Riverdale', 'Dyker Heights', 'Bergen Beach', 'Castleton Corners',
       'Todt Hill', 'Westchester Square', 'Howland Hook', 'Douglaston',
       'Bay Terrace', 'Midland Beach', 'Mariners Harbor', 'Rossville',
       'Holliswood', 'Mill Basin', 'Castle Hill', 'Graniteville',
       'Dongan Hills', 'Neponsit', 'Huguenot', 'South Beach',
       'New Springville', 'Belle Harbor', 'Van Nest', 'Olinville',
       'Jamaica Hills', 'East Morrisania', 'Eltingville', 'Oakwood',
       'West Farms', "Prince's Bay", 'Shore Acres', 'Richmondtown',
       'Spuyten Duyvil', 'Lighthouse Hill', "Bull's Head", 'Co-op City',
       'Rosebank'], dtype=object)

In [ ]:
df['room_type']

0           Private room
1        Entire home/apt
2        Entire home/apt
3            Shared room
4            Shared room
              ...
34221    Entire home/apt
34222       Private room
34223    Entire home/apt
34224       Private room
34225    Entire home/apt
Name: room_type, Length: 34226, dtype: object

In [ ]:
df['total_listings'] = round(df['availability_365'] / df['price'], 3)

In [ ]:
df.head(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,total_listings
0,5728806,Large private room in Nolita,4271676,Nat,Manhattan,Nolita,40.72217,-73.99481,Private room,120,7,3,2015-09-01,0.06,3,0,0.000
1,2243769,Super Bowl New York City Apartment,11460768,Brian,Manhattan,Upper West Side,40.80020,-73.96045,Entire home/apt,1500,1,0,NaN,NaN,1,0,0.000
2,35515415,COZY APT CLOSE TO LGA & JFK AND TRANSPORTATION,267193767,Jenny,Queens,East Elmhurst,40.75558,-73.89316,Entire home/apt,200,2,4,2019-07-05,4.00,1,365,1.825
3,36202006,Stream-Pressed Paradise (Laundry Room Setup),43392243,Rita,Staten Island,Concord,40.60110,-74.07830,Shared room,30,2,0,NaN,NaN,4,82,2.733
4,3780951,Charming Harlem apartment,16065171,Gina,Manhattan,Harlem,40.81022,-73.94266,Shared room,115,1,16,2019-05-26,0.27,1,365,3.174
5,9944426,Lower Manhattan Luxury,51105827,Dax,Manhattan,Battery Park City,40.71192,-74.01572,Entire home/apt,225,90,1,2016-03-18,0.02,1,362,1.609
6,19786915,Spacious Clean Studio Apartment,86892032,Marian,Queens,Rosedale,40.65766,-73.72838,Entire home/apt,60,1,57,2019-07-08,2.41,1,336,5.600
7,22368751,Bright Luxury Apartment with Amazing View of City,20800727,Amirhos,Brooklyn,Fort Greene,40.69064,-73.97898,Entire home/apt,200,5,0,NaN,NaN,1,0,0.000
8,17174519,Chelsea Brownstone 3 Bedroom House,10590692,Wade,Manhattan,Chelsea,40.74443,-74.00012,Entire home/apt,650,3,35,2019-07-03,1.61,2,179,0.275
9,12705519,Heights Haven,1372942,Drew,Manhattan,Washington Heights,40.83170,-73.94290,Entire home/apt,180,30,6,2017-06-24,0.15,1,0,0.000

In [ ]:
df.drop(['total_listings'], axis = 1, inplace=True)

In [ ]:
df.iloc[1]

id                                                           2243769
name                              Super Bowl New York City Apartment
host_id                                                     11460768
host_name                                                      Brian
neighbourhood_group                                        Manhattan
neighbourhood                                        Upper West Side
latitude                                                     40.8002
longitude                                                  -73.96045
room_type                                            Entire home/apt
price                                                           1500
minimum_nights                                                     1
number_of_reviews                                                  0
last_review                                                      NaN
reviews_per_month                                                NaN
calculated_host_listings_count                                     1
availability_365                                                   0
Name: 1, dtype: object

In [ ]:
df.set_index('host_name', inplace = True)

In [ ]:
df.head()

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
Nat,5728806,Large private room in Nolita,4271676,Manhattan,Nolita,40.72217,-73.99481,Private room,120,7,3,2015-09-01,0.06,3,0
Brian,2243769,Super Bowl New York City Apartment,11460768,Manhattan,Upper West Side,40.80020,-73.96045,Entire home/apt,1500,1,0,NaN,NaN,1,0
Jenny,35515415,COZY APT CLOSE TO LGA & JFK AND TRANSPORTATION,267193767,Queens,East Elmhurst,40.75558,-73.89316,Entire home/apt,200,2,4,2019-07-05,4.00,1,365
Rita,36202006,Stream-Pressed Paradise (Laundry Room Setup),43392243,Staten Island,Concord,40.60110,-74.07830,Shared room,30,2,0,NaN,NaN,4,82
Gina,3780951,Charming Harlem apartment,16065171,Manhattan,Harlem,40.81022,-73.94266,Shared room,115,1,16,2019-05-26,0.27,1,365

In [ ]:
df.iloc[1]

id                                                           2243769
name                              Super Bowl New York City Apartment
host_id                                                     11460768
neighbourhood_group                                        Manhattan
neighbourhood                                        Upper West Side
latitude                                                     40.8002
longitude                                                  -73.96045
room_type                                            Entire home/apt
price                                                           1500
minimum_nights                                                     1
number_of_reviews                                                  0
last_review                                                      NaN
reviews_per_month                                                NaN
calculated_host_listings_count                                     1
availability_365                                                   0
Name: Brian, dtype: object

In [ ]:
df.loc[['Rita', 'Nat']]

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
Rita,36202006,Stream-Pressed Paradise (Laundry Room Setup),43392243,Staten Island,Concord,40.60110,-74.07830,Shared room,30,2,0,NaN,NaN,4,82
Rita,35892874,3 Bedroom Loft Like Triplex 2.5 Bath with Garden.,269970642,Manhattan,Harlem,40.80778,-73.94762,Entire home/apt,200,120,0,NaN,NaN,1,365
Rita,788005,"Spacious 1 Bedroom Apt, Prospect Hts/Park Slope",4153591,Brooklyn,Prospect Heights,40.67708,-73.96649,Entire home/apt,195,4,10,2019-03-16,0.13,1,95
Rita,28927140,Gentleman's Quarters #2,43392243,Staten Island,Concord,40.59972,-74.07701,Private room,35,1,2,2019-06-30,2.00,4,360
Rita,26332143,"Bayridge Clean, Beautiful, Spacious Room",198030672,Brooklyn,Bay Ridge,40.63562,-74.03180,Private room,55,1,4,2018-12-30,0.35,1,156
Rita,22224945,IL TUO APPARTAMENTO PERSONALE IN NEW YORK CITY!!,62068432,Manhattan,Harlem,40.81462,-73.95047,Entire home/apt,80,6,2,2019-03-31,0.10,1,31
Rita,29706277,Vintage first floor private room in a 3 bed apt,57128179,Queens,Rego Park,40.71639,-73.85799,Private room,60,2,12,2019-06-16,1.45,2,19
Rita,28400092,Private Bedroom Minutes To Manhattan,214329835,Queens,Ditmars Steinway,40.77882,-73.90935,Private room,69,2,2,2019-05-06,0.23,2,74
Rita,29689253,Privet Room in GROUND FLOOR apt with FREE parking,57128179,Queens,Rego Park,40.71605,-73.85854,Private room,66,1,24,2019-07-05,2.99,2,327
Rita,33243529,Astoria Bedroom 20 minutes away from the city,214329835,Queens,Ditmars Steinway,40.77761,-73.90919,Private room,69,2,1,2019-06-17,1.00,2,349
Rita,10502523,Private Room For 1 w/ Separate Entrance Studen...,43392243,Staten Island,Concord,40.60077,-74.07788,Private room,35,4,73,2019-05-01,2.10,4,320
Rita,28927290,Gentleman's Quarters,43392243,Staten Island,Concord,40.59934,-74.07836,Private room,35,1,45,2019-07-07,4.89,4,177
Nat,5728806,Large private room in Nolita,4271676,Manhattan,Nolita,40.72217,-73.99481,Private room,120,7,3,2015-09-01,0.06,3,0
Nat,22575619,"Cozy, Humble and private",80824522,Brooklyn,Bushwick,40.70250,-73.93253,Private room,69,2,16,2019-06-29,1.07,2,185
Nat,30672441,Brooklyn Pvt Bedroom with an amazing rooftop!,229588502,Brooklyn,Williamsburg,40.71251,-73.96062,Private room,80,3,0,NaN,NaN,1,0
Nat,5372082,Cozy Vacation Getaway,20806507,Brooklyn,Boerum Hill,40.68558,-73.98175,Entire home/apt,100,2,8,2018-07-02,0.17,1,359
Nat,27941636,Beautiful apartment 3 subway stops from Manhat...,211069875,Brooklyn,Borough Park,40.64280,-73.99297,Private room,70,1,0,NaN,NaN,1,0
Nat,13475688,private entrance mini apt! part of my home,84557,Brooklyn,Bedford-Stuyvesant,40.68988,-73.93136,Entire home/apt,85,5,42,2019-06-20,1.27,1,52

In [ ]:
df['neighbourhood_group'].value_counts()

Manhattan        15193
Brooklyn         14033
Queens            3985
Bronx              767
Staten Island      248
Name: neighbourhood_group, dtype: int64

In [ ]:
bronx = df[df['neighbourhood_group'] == 'Bronx']

In [ ]:
bronx = df[df['neighbourhood_group'] == 'Bronx']

In [ ]:
df[(df['neighbourhood_group'] == 'Bronx') & (df['price'] > 175) & (df['minimum_nights']) ].head()

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
Eliu,19038705,Chic Clason Point Condo,17122534,Bronx,Clason Point,40.80652,-73.85312,Entire home,350,3,1,2018-08-27,0.09,1,0
Deon,26147702,YANKEE BASEBALL STAY,158215530,Bronx,Concourse,40.82714,-73.92528,Private room,200,1,0,NaN,NaN,2,179
Armando,34544304,Artistic Home Near Metro with Backyard/Balcony,23878336,Bronx,Fordham,40.86952,-73.89447,Entire home,223,3,0,NaN,NaN,10,315
Sherril,32234982,Magical Mott Haven Loft,241883660,Bronx,Port Morris,40.80707,-73.92974,Entire home,200,5,1,2019-05-25,0.67,1,0
Karmesha,1934765,"One Bedroom Apt, Suitable for Two",10012271,Bronx,Parkchester,40.83645,-73.86634,Entire home,195,5,1,2015-01-01,0.02,1,0

In [ ]:
df['room_type'] = df['room_type'].apply(lambda x: x.strip('/apt'))

In [ ]:
df.head()

,id,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_name,,,,,,,,,,,,,,,
Nat,5728806,Large private room in Nolita,4271676,Manhattan,Nolita,40.72217,-73.99481,Private room,120,7,3,2015-09-01,0.06,3,0
Brian,2243769,Super Bowl New York City Apartment,11460768,Manhattan,Upper West Side,40.80020,-73.96045,Entire home,1500,1,0,NaN,NaN,1,0
Jenny,35515415,COZY APT CLOSE TO LGA & JFK AND TRANSPORTATION,267193767,Queens,East Elmhurst,40.75558,-73.89316,Entire home,200,2,4,2019-07-05,4.00,1,365
Rita,36202006,Stream-Pressed Paradise (Laundry Room Setup),43392243,Staten Island,Concord,40.60110,-74.07830,Shared room,30,2,0,NaN,NaN,4,82
Gina,3780951,Charming Harlem apartment,16065171,Manhattan,Harlem,40.81022,-73.94266,Shared room,115,1,16,2019-05-26,0.27,1,365

In [ ]:
def square(x):
  return x**2

In [ ]:
df['minimum_nights'].apply(square)

host_name
Nat          49
Brian         1
Jenny         4
Rita          4
Gina          1
             ..
Sophie       25
Gabi          1
Mary          4
Olu Bliss     9
Ashton       16
Name: minimum_nights, Length: 34226, dtype: int64

In [ ]:
df.groupby('neighbourhood_group')[['price']].mean().sort_values(by = 'price', ascending= True)

                          price
neighbourhood_group
Bronx                 88.146023
Queens                98.661731
Staten Island        118.491935
Brooklyn             125.868880
Manhattan            197.233002